
{% set name = "heelo" %}
{% set version = "4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 2.0
  git_url: https://github.com/ChunjieShawn/pybuild.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - heelo2
  host:
    - pip
    - python
  run:
    - openssl >=3.0.0
    - python >=3.8

about:
  home: 
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
