
{% set name = "heelo" %}
{% set version = "4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 4.0
  git_url: https://github.com/ChunjieShawn/pybuild.git

build:
  number: 0
  script: ""

requirements:
  build:
    - heelo2
  host:
    - heelo2
    - pip
    - python
  run:
    - heelo2
    - python >=3.7

about:
  home: 
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
