
{% set name = "heelo" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v1.0
  git_url: https://github.com/ChunjieShawn/pybuild.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: 
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit